
import Usuario.Usuario;
import java.util.ArrayList;
import libreriaroiyago.Llamar;
import Escritura.*;
import Lectura.Lectura;
import javax.swing.JOptionPane;
/**
 *
 * @author yagos
 */
public class Fondo extends javax.swing.JFrame {

    /**
     * Creates new form Fondo
     */
    public Fondo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_CodigoPostal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_DNI = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Correo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTOR DE USUARIOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 210, -1));

        jLabel3.setText("Código Postal:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        txt_CodigoPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CodigoPostalActionPerformed(evt);
            }
        });
        txt_CodigoPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CodigoPostalKeyTyped(evt);
            }
        });
        getContentPane().add(txt_CodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 210, -1));

        jLabel4.setText("DNI:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        text_DNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                text_DNIKeyTyped(evt);
            }
        });
        getContentPane().add(text_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 200, -1));

        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 200, -1));

        jLabel5.setText("Télefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        txt_Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CorreoKeyTyped(evt);
            }
        });
        getContentPane().add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 210, -1));

        jLabel6.setText("Correo Eléctronico:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        txt_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_fechaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, 200, -1));

        jLabel7.setText("Fecha Nacimiento:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        jButton1.setText("Añadir Usuario:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/46017.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 634));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void text_DNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_DNIKeyTyped
        
        String dni = null;
        boolean ok = false;
       
            dni = text_DNI.getText();
            if (dni.length() == 9) {
                String numerosStr = dni.substring(0, 8);
                String letra = dni.substring(8);
                int numeros;
                try {
                    numeros = Integer.parseInt(numerosStr);
                    if (Character.isLetter(letra.charAt(0))) {
                        letra = letra.toUpperCase();
                        int resto = numeros % 23;
                        switch (resto) {
                            case 0:
                                if (!letra.equals("T")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 1:
                                if (!letra.equals("R")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 2:
                                if (!letra.equals("W")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 3:
                                if (!letra.equals("A")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 4:
                                if (!letra.equals("G")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 5:
                                if (!letra.equals("M")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 6:
                                if (!letra.equals("Y")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 7:
                                if (!letra.equals("F")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 8:
                                if (!letra.equals("P")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 9:
                                if (!letra.equals("D")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 10:
                                if (!letra.equals("X")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 11:
                                if (!letra.equals("B")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 12:
                                if (!letra.equals("N")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 13:
                                if (!letra.equals("J")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 14:
                                if (!letra.equals("Z")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 15:
                                if (!letra.equals("S")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 16:
                                if (!letra.equals("Q")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 17:
                                if (!letra.equals("V")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 18:
                                if (!letra.equals("H")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 19:
                                if (!letra.equals("L")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 20:
                                if (!letra.equals("C")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 21:
                                if (!letra.equals("K")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            case 22:
                                if (!letra.equals("E")) {
                                    System.out.println("El DNI introducido es falso");
                                    dni = null;
                                } else {
                                    ok = true;
                                }
                                break;
                            default:
                                break;
                        }
                    } else {
                        System.out.println("Formato del DNI incorrecto");
                        dni = null;
                    }
                } catch (NumberFormatException nfex) {
                    System.out.println("Formato del DNI incorrecto");
                    dni = null;
                }
            }
            //verificar que el dni no se encuentre ya en la base de datos
        

    }//GEN-LAST:event_text_DNIKeyTyped

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char c= evt.getKeyChar();
        if((c<'a'|| c>'z') && (c<'A' ||  c>'Z') && (c<' ' || c>' ')) evt.consume();
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
       char d=evt.getKeyChar();
       if((d<'0'||d>'9')) evt.consume();
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void txt_CodigoPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CodigoPostalActionPerformed
  
    }//GEN-LAST:event_txt_CodigoPostalActionPerformed

    private void txt_CodigoPostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CodigoPostalKeyTyped
        char c= evt.getKeyChar();
        if((String.valueOf(c).length() == 5))evt.consume();
    }//GEN-LAST:event_txt_CodigoPostalKeyTyped

    private void txt_CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CorreoKeyTyped
        String c=evt.paramString();
        String correo = null;
        while (correo == null) {
            correo = txt_Correo.getText();
            if (correo.contains("@")) {
                //validar que no tiene más de 1 "@"
                int contA = 0;
                for (int i = 0; i < correo.length(); i++) {
                    if (correo.charAt(i) == '@') {
                        contA++;
                    }
                }
                if (contA == 1) {
                    // continuación de las validaciones
                    String[] lista = correo.split("@");
                    //validar que el dominio no tiene más de un punto
                    int contP = 0;
                    for (int i = 0; i < lista[1].length(); i++) {
                        if (lista[1].charAt(i) == '.') {
                            contP++;
                        }
                    }
                    if (contP == 1) {
                        //continuacion de las validaciones
                        String[] dominio = lista[1].split("\\.");
                        //validar el tipo
                        if (dominio[1].equals("es") || dominio[1].equals("com") || dominio[1].equals("org")) {
                        }else {
                            JOptionPane.showMessageDialog(null,"Tipo del dominio erróneo");
                            correo = null;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null,"Formato del dominio incorrecto");
                        correo = null;
                    }
                } else {
                    JOptionPane.showMessageDialog(null,"Formato del correo incorrecto");
                    correo = null;
                }
            }else {
                JOptionPane.showMessageDialog(null,"Formato del correo incorrecto");
                correo = null;
            }
        }
      
    }//GEN-LAST:event_txt_CorreoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cadena2,cadena3,cadena4,cadena5,cadena6,cadena7;
        cadena2=txt_nombre.getText();
        cadena3=text_DNI.getText();
        cadena4=txt_Correo.getText();
        cadena5=txt_CodigoPostal.getText();
        cadena6=txt_telefono.getText();
        cadena7=txt_fecha.getText();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_fechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fechaKeyTyped
         int mes = 0;
        while (mes == 0) {
            try {
                mes = Llamar.lerInt("Fecha de nacimiento\nMes:");
                if (mes < 1 || mes > 12) {
                    System.out.println("Mes inválido");
                    mes = 0;
                }
            } catch (NumberFormatException ex) {
                System.out.println("El formato debe ser numérico");
                mes = 0;
            }
        }
        int anho = 0;
        while (anho == 0) {
            try {
                anho = Llamar.lerInt("Fecha de nacimiento\nAño:");
                if (anho < 1910 || anho > 2050) {
                    System.out.println("Año fuera del límite permitido");
                    anho = 0;
                }
            } catch (NumberFormatException ex) {
                System.out.println("El formato debe de ser numérico");
                anho = 0;
            }
        }
        int dia = 0;
        while (dia == 0) {
            try {
                dia = Llamar.lerInt("Fecha de nacimiento\nDía:");
                switch (mes) {
                    case 1:
                    case 3:
                    case 5:
                    case 7:
                    case 8:
                    case 10:
                    case 12:
                        if (dia < 1 || dia > 31) {
                            System.out.println("Día incorrecto");
                            dia = 0;
                        }
                        break;
                    case 4:
                    case 6:
                    case 9:
                    case 11:
                        if (dia < 1 || dia > 30) {
                            System.out.println("Día incorrecto");
                            dia = 0;
                        }
                        break;
                    case 2:
                        if ((anho % 4)==0 && (anho % 100)!=0) {
                            if (dia < 1 || dia > 29) {
                                System.out.println("Día incorrecto");
                                dia = 0;
                            }
                        } else {
                            if ((anho % 100)==0 && (anho % 400)==0) {
                                if (dia < 1 || dia > 29) {
                                    System.out.println("Día incorrecto");
                                    dia = 0;
                                }
                            } else {
                                if (dia < 1 || dia > 28) {
                                    System.out.println("Día incorrecto");
                                    dia = 0;
                                }
                            }
                        }
                        break;
                    default:
                        break;
                }
            } catch (NumberFormatException ex) {
                System.out.println("El formato debe de ser numérico");
            }
        }

        String fecha = dia+"/"+mes+"/"+anho;
    }//GEN-LAST:event_txt_fechaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fondo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fondo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField text_DNI;
    private javax.swing.JTextField txt_CodigoPostal;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
